### ISSUE TITLE
Deprecation warning in Mendix 7: mendix.lang.nullExec

### ISSUE THREAD

**Issue by axelbrink** [Mcpoowl/FaviconBadge#6]
DEPRECATED: mendix.lang.nullExec. Use plain javascript if instead -- will be removed in version: 9.0

This warning keeps filling the logging in Mendix 7. Would be great if you could fix this.

**Comment by Mcpoowl** [comment]
Hi @axelbrink I've made a new release on GitHub. Can you check it out and see if it fixes it? It's not available in the AppStore yet, so you'll have to download it from here.

**Comment by axelbrink** [comment]
Thanks for helping Mcpoowl. There is an issue with this file. An error occurs when Mendix tries to read it:
```
Package 'C:\_NoBackup\<***>\widgets\FaviconBadge.mpk': File does not seem to be a valid ZIP file.
Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0xAFBC7A37) at position  0x00000000
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile.Read(String fileName, TextWriter statusMessageWriter, Encoding encoding, EventHandler`1 readProgress)
   at Mendix.Modeler.WebUI.WidgetPackages.WidgetPackageImporter.ImportPackage(String packageFilePath) in C:\jenkins-ci\workspace\AppStudio3.0-Build@4\modeler\Mendix.Modeler.WebUI\WidgetPackages\WidgetPackageImporter.cs:line 75
```

**Comment by Mcpoowl** [comment]
@axelbrink I've updated the release with a new zip (it was of 7zip format instead of zip..) Can you try again?

**Comment by axelbrink** [comment]
The .mpk file loads correctly now, but the deprecation warning is still there.

**Comment by Mcpoowl** [comment]
With what .mpk file are you getting the deprecation warning? And what version of the modeler? In my project (7.23.7) the widget doesn't even want to load 😂

**Comment by axelbrink** [comment]
The widget does not load in a new project in Mendix 7.23.8: "Could not create widget FaviconBadge.widget.FaviconBadge" appears in the browser. Strangely, the widget does work in an existing project, but there it causes the deprecation message.
